box: 		"http://wwwuser.gwdg.de/~pkasprz/vagrant-ubuntu-14.04.box"
domain: 	""

ip_suffix: 1

networks:
  interface1: 
    ip: 	    "10.<%= environment %>.254.<%= ip_suffix %>"
    netmask: 	"255.255.255.0"
    type:	    "private_network"